# Which docker image should be used to deploy
DOCKER_TAG: "ghcr.io/netcracker/qubership-testing-platform-itf-reporting:4.4.112"
# This option turns on or off logging in graylog
GRAYLOG_ON: "false"
# This option turns on or off kafka enable
KAFKA_ENABLE: "false"
KAFKA_REPORTING_SERVERS: ""
# Keycloak enabled
KEYCLOAK_ENABLED: "false"
# IP of db
PG_DB_ADDR: "my-postgres-postgresql"
# Spring profile for security
SPRING_PROFILES: "disable-security"
keepHookLogs: true
HELPER_IMAGE: "ghcr.io/netcracker/qubership-testing-platform-helm-hook-helper:main-20250714085543"
CONTENT_SECURITY_POLICY: "*"
pg_pass: "postgrestest"
pg_user: "postgres"
EUREKA_CLIENT_ENABLED: "false"
ATP_SERVICE_PUBLIC: "false"
ATP_SERVICE_INTERNAL: "false"
ATP_ITF_BROKER_URL_TCP: "tcp://activemq-broker:61616"
ACTIVEMQ_PORT_PARAM: "61616"
EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
JBOSS_THREADS_EQE_STATISTICS: "false"
ITF_REPORTING_DB_USER: "reporting_itf_reporting"
ITF_REPORTING_DB_PASSWORD: "reporting_itf_reporting"